---

- name: 'Runplaybook-bootstrap_python.yml'
  ansible.builtin.import_playbook: playbook-bootstrap_python.yml

- name: 'Run playbook-install_k3s.yml'
  ansible.builtin.import_playbook: playbook-install_k3s.yml

- name: 'Run playbook-k3s_configure_private_registries.yml'
  ansible.builtin.import_playbook: playbook-k3s_configure_private_registries.yml

- name: 'Run playbook-traefik_installation.yml'
  ansible.builtin.import_playbook: playbook-traefik_installation.yml

- name: 'Run playbook-postgresql_installation.yml'
  ansible.builtin.import_playbook: playbook-postgresql_installation.yml

- name: 'Run playbook-cert-manager_installation.yml'
  ansible.builtin.import_playbook: playbook-cert-manager_installation.yml

- name: 'Run playbook-olm_installation.yml'
  ansible.builtin.import_playbook: playbook-olm_installation.yml

- name: 'Run playbook-gitlab-operator_installation.yml'
  ansible.builtin.import_playbook: playbook-gitlab-operator_installation.yml

- name: 'Run playbook-gitlab_installation.yml'
  ansible.builtin.import_playbook: playbook-gitlab_installation.yml
